version: 0.2

phases:
  install:
    commands:
      - echo Installing dependencies...
      - npm install

  build:
    commands:
      - echo Building the React app...
      - npm run build     # generates dist/ folder

  post_build:
    commands:
      - echo Build completed successfully.
      - echo Preparing artifacts for S3 upload...

artifacts:
  files:
    - '**/*'
  base-directory: dist   # Upload ONLY the build output
